mod types;

use wasm_bindgen::prelude::*;
use js_sys::Array;

use harmoni_core::api::{self, GenerateOptions};
use harmoni_core::ColorInput;

fn to_js_error(e: impl std::fmt::Debug) -> JsError {
    JsError::new(&format!("Invalid color input: {:?}", e))
}

fn array_to_lightness(js_array: Array) -> Result<[f32; 10], JsError> {
    if js_array.length() != 10 {
        return Err(JsError::new(&format!(
            "Lightness array must have exactly 10 values, got {}",
            js_array.length()
        )));
    }

    let mut lightness = [0.0f32; 10];
    for i in 0..10 {
        let value = js_array.get(i as u32);
        let f = value
            .as_f64()
            .ok_or_else(|| JsError::new(&format!("Lightness at index {} is not a number", i)))?
            as f32;
        lightness[i] = f;
    }

    Ok(lightness)
}

fn palette_to_js(palette_data: harmoni_core::Palette) -> Result<Palette, JsError> {
    let wrapped: types::Palette = palette_data.into();
    serde_wasm_bindgen::to_value(&wrapped)
        .map(|v| v.unchecked_into())
        .map_err(|e| JsError::new(&e.to_string()))
}

// Palette is generated by Tsify as a struct interface:
// { swatches: Swatch[], max_recommended_light_padding: number, ... }
// Tsify automatically emits this to the generated .d.ts file via the
// #[tsify] derive on `types::Palette`.

#[wasm_bindgen]
extern "C" {
    // Opaque JS handle whose TS type is `Palette` (= Swatch[]).
    // Needed because Vec<T> is not a first-class wasm-abi return type.
    #[wasm_bindgen(typescript_type = "Palette")]
    pub type Palette;
}

#[wasm_bindgen]
pub fn get_contrast_rating(bg: &str, fg: &str) -> Result<types::ContrastResult, JsError> {
    api::audit_contrast(
        ColorInput::Css(bg.to_string()),
        ColorInput::Css(fg.to_string()),
    )
    .map(Into::into)
    .map_err(to_js_error)
}

#[wasm_bindgen]
pub fn generate_palette(
    hex: &str,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_palette_with_lightness(
    hex: &str,
    lightness: Array,
    light_padding: f32,
    dark_padding: f32,
) -> Result<Palette, JsError> {
    let lightness_curve = array_to_lightness(lightness)?;

    let palette_data = api::generate_with_lightness(
        ColorInput::Css(hex.to_string()),
        lightness_curve,
        GenerateOptions {
            light_padding,
            dark_padding,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_palette_with_light_padding(
    hex: &str,
    light_padding: f32,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_with_options(
        ColorInput::Css(hex.to_string()),
        GenerateOptions {
            light_padding,
            dark_padding: 0.0,
            ..GenerateOptions::default()
        },
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn generate_greyscale_oklch() -> Palette {
    let data = api::generate_greyscale();
    let wrapped: types::Palette = data.into();
    serde_wasm_bindgen::to_value(&wrapped)
        .expect("serializing greyscale palette should never fail")
        .unchecked_into()
}

#[wasm_bindgen]
pub fn generate_neutral_ramp(
    white: &str,
    black: &str,
    tint: types::TintMode,
) -> Result<Palette, JsError> {
    let palette_data = api::generate_neutral_ramp(
        ColorInput::Css(white.to_string()),
        ColorInput::Css(black.to_string()),
        tint.into(),
    )
    .map_err(to_js_error)?;

    palette_to_js(palette_data)
}

#[wasm_bindgen]
pub fn derive_soft_neutrals(
    brand: &str,
    softness: f32,
) -> Result<types::SoftNeutrals, JsError> {
    api::derive_soft_neutrals(ColorInput::Css(brand.to_string()), softness)
        .map(Into::into)
        .map_err(to_js_error)
}
